### PR TITLE
standardizing the coding conventions to the rest of the repo

### PR DESCRIPTION
**Pull request by jvanasco**
This is the last repo in my housekeeping push to standardize the coding conventions and developer guidelines across the 'sqlalchemy' orgs various libraries.

**This is not tested, as I don't have access to ms access**

This is unfortunately also the biggest changeset, as it did not already use `black` or pre-commit, so this absolutely needs a review.

### CODE REVIEW

**Comment by oshawa-connection** [comment]
Hi, I'd be more than willing to run the tests - I've got access versions 2010 and 365 32 bit version installed.

**Comment by gordthompson** [comment]
I ran the suite tests and found a couple of new ones that were failing. Fixes here:

https://github.com/jvanasco/sqlalchemy-access/pull/1

**Review by gordthompson — APPROVED** [review]
I'm not (yet) a fan of automated arbitrary code re-formatting, and IMO hard limit of 79 characters per line is rather silly, but I'm willing to go with the flow on this one.

**Comment by jvanasco** [comment]
@gordthompson "black" finally won me over, but the I hear you on the 79 characters. SqlAlchemy and most of the other repos in the org have adopted it, so I decided to invest some spare cycles on standardizing everything to the same conventions and config files.

fwiw, the big thing that won me over with "black": it made an incredibly large and unruly testing suite actually manageable for changes.

**Comment by zzzeek** [comment]
the -l 79 *really* keeps us honest as far as code organization.  Since Python is a language where indentation is a direct indicator of cyclomatic complexity, if we find ourselves fighting the 79 char indentation a lot somewhere, that often means we have too much nesting going on anyway.

as for the automatic.   what it means is, I can type my code in a totally sloppy fashion and do whatever I want, and black will ensure it is formatted consistently.   black operates on the entire file at once though, so it is important that the **whole** file be organized in this way.  if it isn't, then as I'm working on a few lines in a file, the code formatter will go and reformat other lines producing unrelated artifacts in the merge.    But this is actually a good thing.  Black attacking the whole file rather than just the part that I changed means there is no ambiguity in how any particular part of a file must be formatted; it's not only linted by the flake8 linter but it's completely deterministic by the black formatter.   I don't have to argue with contributors how certain code should be formatted, I don't have to occasionally change how things are formatted to suit some new style we want to do, and I can run it on a whole repo without issue.    It eliminates a whole class of merge conflicts as well, as I've had to spend lots of time dealing with merge conflicts because of different formatting approaches across branches, etc..     It also helps readability by reducing the possibilities for code formatting so that patterns are more quickly recognizable.   

I really was looking for *years* for tools that can automatically format code and save me hours of typing, and while there are many, only black's heavy-handed approach actually works.   https://www.mattlayman.com/blog/2018/python-code-black/

**Comment by zzzeek** [comment]
both the "zimports" tool I wrote, and the black thing, you might note have a heavy emphasis on more, shorter lines.    Particularly with the imports thing which I got from openstack, that's all about merges.   If I add an import, and you add an import, and they both happen to be on a single line that is "from sqlalchemy import A, B", that's a merge conflict.   The single-import-per-line is the only way to get around that.  similarly, having them sorted **deterministically** reduces merge conflicts as much as possible.

**Comment by zzzeek** [comment]
the whole thing with the separate "changelog" file, that's also about eliminating merge conflicts.  I tried every possible way of getting around that, but git merges always produces conflicts for line-level changes.  Even though git allows different merge strategies, the other ones don't work much better and Gerrit only supports the regular "diff" merge.   

so all these weird patterns and tools you see me using, these are all the result of years of banging my head against the wall with other techniques.   nobody is more tool-phobic than me so you can be sure all these things I'm doing are working **really** well :)

**Comment by jvanasco** [comment]
@zzzeek can you explain again, or point to existing docs, on the changelog thing. i'm just not understanding it, and I'd like to stop making things harder for you.

**Comment by zzzeek** [comment]
it's hard to explain.

the general markup format is at: https://github.com/sqlalchemyorg/changelog however this does not document the changelog-per-file part of it.

the changelog-per-file thing is inspired from reno: https://docs.openstack.org/reno/2.5.0/user/usage.html

the crazy part then is, suppose I have a change that I'm going to commit to the 1.3 and the 1.2 branch.  I want the changelog for both 1.2 and 1.3 to show, "Fixed the XYZ bug", in the 1.3 vresion I want it to say, "Also backported to 1.2", and finally I want to type all of this only once, and have the patch be character-compatible with both the 1.3 and the 1.2 branches.   Noting that in SQLAlchemy, every release contains the full set of changelog files for every version prior to that.   

So the idea was that, if the change is going to be backported in 1.2, we put it in the unreleased_12/ folder, and it lives in the same place in both the 1.3 and the 1.2 branch.  That way it shows up in the changelog_12.rst file, and if i want it to also show up in changelog_13.rst, I add a ":version:" directive indicating that.

As it turns out, I've been "Backporting" a lot less between released versions than I thought I would (this also means i think we might want to revisit the classifications we have up at https://www.sqlalchemy.org/download.html#relstatus because I have zero intention of ever putting out a 1.2 release).   

So when I fix a bug in master right now (which is 1.4), but the bug is also going to be backported to the current 1.3 series, I put the changelog file in unreleased_13/ so that when I cherry-pick the change from master to 1.3, the file doesn't produce the merge conflict that it would if it had been in unreleased_14, which doesnt exist in the 1.3 branch, and it comes right out in the changelog_13.rst file.

There's also a whole thing about those files getting rolled up into the changelog_XY.rst file on each release, which is more that's not documented right now, and even more stuff involving how the changelogs get published to github's "releases", even more tools I wrote for that.    But start with the first three main things above first :).

**Comment by jvanasco** [comment]
i think i get it...

1. make a ticket to get assigned a number (or make a PR, then use that number)
2. write the ticket's changelog data into a new file `/doc/build/changelog/unreleased_xx/{TICKET}.rst`
3. do not touch `changelog_{version}.rst`
4.  let @zzzeek handle moving the `{TICKET}.rst` file or integrating it in other ways.

is that about right?

**Comment by zzzeek** [comment]
so yes, you just put unreleased_xx/ticket.rst files in.    the content of those files gets put into the "changelog" file at release time using this: https://github.com/sqlalchemyorg/changelog/blob/master/changelog/cmd.py#L11

**Pull request merged**
